### ISSUE TITLE
General comments

### ISSUE THREAD

**Issue by taldcroft** [sot/aca_lts_eval#1]
- It would have been good to start the life of this code with a PR to easily allow comments.
- Don't repeat yourself.
- Don't prematurely optimize.
- Don't overconfigurate.
- Most or all your uses of `global` are not needed.  One clears a global dict in place with GLOBAL.clear().
- I'd be happier with `t_ccd` instead of `temp`, which pretty much always maps to temporary in my head.

**Comment by jeanconn** [comment]
> It would have been good to start the life of this code with a PR to
> easily allow comments.

Is the convention on that to PR to the empty project?  I was planning to
ping about that and move the work so far into a feature branch to PR for
feedback...  after I'd at least cleaned up the globals.

**Comment by jeanconn** [comment]
> Don't repeat yourself.

Where am I most guilty of that?   Not aware enough of that to address the
issue as well as I'd like.

**Comment by jeanconn** [comment]
Re "I'd be happier with t_ccd instead of temp, which pretty much always maps to temporary in my head", is that only for the code, or do you want to rename the project too?  This kind of made sense to me but I'm just throwing ideas up here to make some progress.

**Comment by taldcroft** [comment]
Yes, you should rename the project, but think of a nice happy short name in the flavor of existing projects like pyger, kadi, mica.

**Comment by taldcroft** [comment]
> Where am I most guilty of that?   Not aware enough of that to address the issue as well as I'd like.

Work on training yourself to spot places where code or code segments are repeated at least two or three times and refactor.  As part of your training, start scanning down the code and find the one case I was complaining out.  As a clue, note also that a tuple of floats is a perfectly good hash key.

**Comment by taldcroft** [comment]
I guess we haven't previously had a convention about starting a new project, but let's make it so.  So you should reset master to be empty and make an Initial code PR.

**Comment by taldcroft** [comment]
Part of my goal in suggesting using a vector is to encourage you to think more functionally rather than procedurally.  This is tied in with the idea of not prematurely optimizing.  You are quite good at writing tricky procedural code that works reliably, but it's hard for me to read and convince myself it is working.  This is the example I am thinking about:

```
    best_temp = None
    best_roll = None
    rolldev = get_rolldev(day_pitch)
    # Quat doesn't care about the domain of roll, so I don't have to
    # do anything tricky with 180/360 etc
    for rolldiff in np.arange(0, rolldev, step=.5):
        # Walk out from nom_roll instead of just through the range,
        # and quit if we get one that is at the warm limit
        # That will give us the closest-to-nominal best choice
        for roll in [nom_roll - rolldiff, nom_roll + rolldiff]:
            roll_temp = max_temp(ra, dec, roll, time=time)
            if roll_temp is not None:
                if best_temp is None or roll_temp > best_temp:
                    best_temp = roll_temp
                    best_roll = roll
                if best_temp == characteristics.WARM_T_CCD:
                    break
```

First, this depends on a sentinel value of `None` coming from `max_temp`, which starts me off confused.  So the first thing is to get rid of that sentinel value by simply recognizing 0 stars as one of the possible results.  There is nothing conceptually different between 0 stars and 1 star or 2 stars.  They are all going to have a `t_ccd` of COLD_T_CCD and result in rejection.  From there here is a functional approach:

```
# Make an array like [0, -1, 1, -2, 2, ... -14, 14]
D_ROLL = 1.0
plus_minus_rolls = [[-r, r] for r in range(D_ROLL, max_off_nom_roll(pitch), D_ROLL)]
off_nom_rolls = np.concatenate([[0]] + plus_minus_rolls)

# Compute max allowed T_ccd at each roll
rolls = nom_roll + off_nom_rolls
t_ccds = [max_t_ccd(ra, dec, roll, time=time) for roll in rolls]  # optimize later if needed

# Find the location of the warmest allowed temperature for all rolls
i = np.argmax(t_ccds)  # In case of multiple equal max values, the first occurrence wins.

# Return the roll and max_t_ccd for nominal and best roll cases
return rolls[0], t_ccds[0], rolls[i], t_ccds[i]
```

**Comment by taldcroft** [comment]
There are metrics of code complexity and generally speaking the levels of indentation play a big role.  The procedural version has 4 levels of indentation while the functional implementation has 0.  That's why I'm harping on this.

**Comment by jeanconn** [comment]
> First, this depends on a sentinel value of None coming from max_temp,
> which starts me off confused.

Yes,  I know that code is all crap.

**Comment by jeanconn** [comment]
> Work on training yourself to spot places where code or code segments are
> repeated at least two or three times and refactor. As part of your
> training, start scanning down the code and find the one case I was
> complaining out. As a clue, note also that a tuple of floats is a perfectly
> good hash key.

Stumped.  I've got two hashes left.   One using the tuple you recommended,
one unnecessary one of all the temperatures and rolls that is an artifact
of not looking up a non clunky way to build an astropy table a row at a
time.  Not sure where either qualifies as gross code duplication.  Hmm.

**Comment by jeanconn** [comment]
> I guess we haven't previously had a convention about starting a new
> project, but let's make it so. So you should reset master to be empty and
> make an Initial code PR.

I thought perhaps I could just move new_master to master.   Now that I've
referenced  your comments from the PR they should not get orphaned even of
those master commits dissappear.

**Comment by taldcroft** [comment]
```
    if "{:.8f}_{:.8f}".format(ra, dec) in AGASC_CACHE:
        field = AGASC_CACHE["{:.8f}_{:.8f}".format(ra, dec)]
    AGASC_CACHE["{:.8f}_{:.8f}".format(ra, dec)] = field
```

**Comment by jeanconn** [comment]
Yes, I was planning to chuck all of that agasc cache code both because it
was badly written and because the cache seemed unnecessary in this case (as
the "magic" of the shared data was not a big savings in complexity over
just passing the stars around functionally).  Gone in the PR.

**Comment by taldcroft** [comment]
OK, the `new_master` strategy works and presumably we then merge that into master at the end.

**Comment by jeanconn** [comment]
I think I've addressed these issues or opened them as new github issues on the project, so closing this.
