### ISSUE TITLE
Evaluate changes for dynamic offset transition

### ISSUE THREAD

**Issue by jeanconn** [sot/aca_lts_eval#28]
I'll have to review to see what should really be changed in here

1) more FOV edge padding to include dynamic variation? 
2) ODB_SI_ALIGN (this is using the old/original ODB_SI_ALIGN value, is that right moving forward?)

**Comment by jeanconn** [comment]
@taldcroft do you have thoughts on this?  I think we're OK on > 99% of targets, but wondered about dynamic variation and the best ways to make conservative (but not overly conservative) catalog predictions for the tough cases.

**Comment by taldcroft** [comment]
You can use a CCD temperature of the planning limit minus 2 degC everywhere and compute ACA offsets accordingly.  That will be sufficiently accurate and reasonably future-proof.

**Comment by jeanconn** [comment]
OK.  That seems reasonable.  I've also got a 60 arcsec manvr error built in to these acquisition star checks, which is already on the generous side.  I'm having a bit of a problem today with wrapping my head around cycle 17 vs 18 offsets.

**Comment by taldcroft** [comment]
As long as you have the cycle, date and OR offsets for each target then it should be straightforward and transparent.

It is probably worth making a new utility function in `chandra_aca.drift` that gets the aimpoint for a given `date`, `cycle`, and `detector`.  This would read the SOT MP zero-offset aimpoint table by default.  One might even have a boolean `too` to mimic the default behavior of the SOT MP routine.

**Comment by jeanconn** [comment]
Right, I was just trying to puzzle out which pointing we are getting now:

https://github.com/sot/aca_required_temp/blob/master/aca_lts_eval.py#L124

**Comment by taldcroft** [comment]
At this moment the code you linked is off by around 12 arcsec due to the operational use of the shifted OFLS CHARACTERISTICS.  When cycle 18 targets are being scheduled it will be off by another ~15-20 arcsec or so.

BTW, you should replace the call to that routine with `chandra_aca.transform.calc_aca_from_targ()`

**Comment by jeanconn** [comment]
> At this moment the code you linked is off by around 12 arcsec due to the operational use of the shifted  OFLS CHARACTERISTICS. 

Yes.  I think we didn't have a good idea where that was going to stabilize when we started this, and didn't have a shifted characteristics handy yet (and I wasn't sure about the wisdom of a plan to redo all of these estimates every few weeks).

> When cycle 18 targets are being scheduled it will be off by another ~15-20 arcsec or so.

That's the part that is confusing me.  I though we were moving back to using the original ODB_SI_ALIGN as the reference?  But I'm probably just not getting enough coffee today.

> BTW, you should replace the call to that routine with chandra_aca.transform.calc_aca_from_targ()

Yes, that's also on my list.  I think this code predates that routine by a few months (or whenever it finally ended up in chandra_aca).

**Comment by taldcroft** [comment]
> When cycle 18 targets are being scheduled it will be off by another ~15-20 arcsec or so.
> 
> > That's the part that is confusing me. I though we were moving back to using the original 
> > ODB_SI_ALIGN as the reference? But I'm probably just not getting enough coffee today.

That 15-20 arcsec was assuming that the code is not changed and ignores the dynamical ACA offsets.  But if the code does the right thing, starting from the cycle-dependent aimpoints and including the ACA offsets via `get_aca_offsets` then it will be within ~10 arcsec with a mean error less than ~5 arcsec.

**Comment by jeanconn** [comment]
OK.  I've started with a [PR to get the right aimpoint](https://github.com/sot/chandra_aca/pull/15)

**Comment by jeanconn** [comment]
Closed by #30
