### ISSUE TITLE
Come up with a better metric for guide stars

### ISSUE THREAD

**Issue by jeanconn** [sot/aca_lts_eval#42]
It sounds like we should just use the ORViewer/starcheck "count" of guide stars and be done with it.  This should be meaningful and easy to optimize (if not particularly sensitive).

It doesn't give us an "OK" temperature for an observation but that's probably OK.

**Comment by jeanconn** [comment]
What are your thoughts on just yay or nay for the field based on this guide star count @taldcroft ?

**Comment by taldcroft** [comment]
The question is how well this correlates with actual catalog pass / fail.  FOT MP is using this product as a thumbs-up indicator for planning in a certain way.

But it does seem better than the alternative of nothing.

**Comment by jeanconn** [comment]
It seems better than the current alternative of using the magnitude of the 4th star as a proxy for an allowed temperature.

**Comment by jeanconn** [comment]
Regarding "The question is how well this correlates with actual catalog pass / fail" since we basically have that just as ACA reviewer opinion, correlation is a little tricky.

**Comment by jeanconn** [comment]
If we replace the "warmest allowed" temperature for guide stars with a yes or no based on count, it does get trickier to optimize over the roll range when combining with the "warmest allowed" temperature for acquisition.  I previously avoided that problem by using the minimum value of either the acq temperature or the guide temperature.  If there is no "guide temperature" we probably need some rule.  

I'll look at some more data, but overall do we think we want the attitude with the best acquisition probability and at least 4 good guide stars, or some hybrid (shooting to get 5 guide stars and an acquisition probability within some value of the best acquisition probability) or something else?

**Comment by jeanconn** [comment]
Wait, how about instead of using a the star_count based on the three mag thresholds (10.0, 10.2, 10.3) we define those as SNR thresholds based on current dark current (making the count function a function of catalog star mags and temperature), and then solve for the max temperature which still has a star count of 4 (our red limit)?

This would give us something much better for guide than the "4th star becomes too faint" metric but would still be a temperature that would describe the overall quality of the catalog.  It would be a bit more "conservative" than our non-temperature-dependent guide star counts in starcheck/ORViewer, but the conservatism should just steer the LTS setup a little bit.  

This method would be more complicated than it probably needs to be to get some number for guide, but I'm not thinking of much better ideas.

**Comment by jeanconn** [comment]
Closed by #44
